### ISSUE TITLE
How to use it in Framework7 with Vuejs?

### ISSUE THREAD

**Issue by red010182** [valnub/Toast-for-Framework7#4]
I don't use `app = new Framework7()`, instead:

```
import Framework7Vue from 'Framework7Vue'
Vue.use(Framework7Vue);

let root = "#app"
new Vue({
  el: root,
  render: h => h(Home),
  framework7: {
      root: root, //Should be same as app el
      animateNavBackIcon: true,
      routes: routes,
      pushState: true,
  }
});

```

In this case, how do I use the toast?

**Comment by valnub** [comment]
Check section "Initialized Instances" in docs: https://framework7.io/vue/init-app.html

**Comment by haris0** [comment]
can you give me example how to use it in Framework7  Vue?

**Comment by valnub** [comment]
@haris0 What version of F7?
If you're on V2, then you can use built-in toast: http://framework7.io/docs/toast.html

**Comment by haris0** [comment]
i'm still using V1, i have some problem to migrate because my app was released

**Comment by valnub** [comment]
@haris0 Within a vue method you can access `this.$f7` to get the f7 app instance.

Hence you can do:

```javascript
new Vue({
    methods: {
        yourMethod: function () {
          var toast = this.$f7.toast('Marked star', '<div>☆</div>', {});
          toast.show();
        }
    },
});
```

See https://framework7.io/vue/vue-component-extensions.html

**Comment by haris0** [comment]
it's not work, 
i was added the script to my project in index.html :

```
<link rel="stylesheet" href="css/toast.css"/>
<script src="js/toast.js"></script>
```
and define method in my main.js : 
```
new Vue({
    el: '#app',
    render: h => h(Splash),
    framework7: {
        root: '#app', //Should be same as app el
        pushState: true,
        . . . 
    },
    methods: {
      makeToast: function () {
        var toast = this.$f7.toast('Marked star', '<div>☆</div>', {});
          toast.show();
      }
  },
```
but when i call method in my page.vue : 

`makeToast()`
or
`this.$f7.makeToast();`

error : 
`self.$f7.makeToast is not a function`
or
`makeToast is not defined`

**Comment by valnub** [comment]
@haris0 

`self.$f7.makeToast(('Marked star', '<div>☆</div>', {}))` is wrong.

It should be `self.$f7.toast('Marked star', '<div>☆</div>', {})` within `makeToast`.

Also, make sure to call `makeToast()` correctly on your vue instance.

**Comment by haris0** [comment]
Yes in main.js already like that

`self.$f7.toast('Marked star', '<div>☆</div>', {}) within makeToast`

should be : 
```
methods: {
      makeToast: function () {
        var toast = this.$f7.toast('Marked star', '<div>☆</div>', {});
          toast.show();
      }
}
```
right?
the problem is when i call method makeToast() in my vue instance, coz when i call like this 
```
mounted(){
     makeToast();
}
```
error 
`makeToast is not defined`

How to call correct method `makeToast()` in my page.vue

**Comment by valnub** [comment]
@haris0 Did you try `this.makeToast()` ? I think `this` should reference the vue instance from any function defined within `methods`.

**Comment by haris0** [comment]
`this.makeToast()` its still not working
but my friend who understand about vue its tell me that use `self.$root.makeToast()`, and it's working correctly,.,

thank you so much for your help @valnub :D
