### ISSUE TITLE
toast is not a function

### ISSUE THREAD

**Issue by martinturner** [valnub/Toast-for-Framework7#5]
Hello, I'm trying to use the toasts for Framework7 but i seem to be getting a problem when i try click on the button, it says the .toast function is not available.
I've added the js and such as you said. But still not working?
Heres my codepen. 
https://codepen.io/mjturner/pen/mwpdVo

**Comment by valnub** [comment]
You need to pass in "true" as a parameter:

`toast.show(true);`

To hide, use `toast.show(false);`

**Comment by valnub** [comment]
The following is wrong with your code:

- HTML malformed (views, pages missing)
- F7 initialization code missing in JS
- F7 files missing (js, css)
- Toast plugin missing (js, css)
- pageInit not called

After fixing this, it worked: https://codepen.io/valnub/pen/PjeZQw

**Comment by martinturner** [comment]
<img width="724" alt="screen shot 2017-07-05 at 10 50 26 am" src="https://user-images.githubusercontent.com/15831323/27848518-d9d9126c-616f-11e7-9ca3-dc2ba16a25b5.png">

Im still getting an error from this, i have put in the code and all the js and css files in the correct places. It works on the codepen, but for some reason not on my Framework7 app, do you see anything else that i may be doing wrong? 
I dont know how its working on the codepen, but not for my app. 
https://codepen.io/mjturner/pen/mwpdVo

**Comment by valnub** [comment]
1. Your HTML looks completely messed up. Lots of opened tags like `<head>` but not closing. Also, no need for using `<head>` in Codepen anyway. Only use `<body>` content!
2. No need to reference scripts from HTML. In Codepen, you do it from Settings pane (See screenshot below).

I fixed it for you here: https://codepen.io/valnub/pen/yXEjPJ?editors=1010

![codepen](https://user-images.githubusercontent.com/3787662/27858419-7167887a-6175-11e7-8fae-20416194f29f.jpg)
